### ISSUE TITLE
Can't set the threads number

### ISSUE THREAD

**Issue by michael-kotliar** [frankligy/scTriangulate#15]
The program either uses a single core or all of them. It would be nice to have a way to set the exact number of cpus to be used

**Comment by frankligy** [comment]
Sure thanks a lot for noticing it, currently I set the default cpu to the number of annotations (number of columns) because this is the most time-consuming step for computing stability metrics for each cluster annotation. (https://github.com/frankligy/scTriangulate/blob/main/sctriangulate/main_class.py#L802-L805), I will put it on my to-do list.

**Comment by frankligy** [comment]
It has been solved in commit (c8ed34689b084dd776d28734acddfa2d65fe4cc9)
